[package]
name = "tictactoe"
version = "0.1.0"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
log = "0.4"
rand = "0.8"
wasm-logger = "0.2"
yew = { version = "0.20.0", features = ["csr"] }
text_io = "0.1.12"
